apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w7cx3vkg6-nodejs 
  janus-idp.io/tekton: w7cx3vkg6-nodejs
  backstage.io/kubernetes-id: w7cx3vkg6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w7cx3vkg6-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  